name: 💡 Feature request
description: Suggest a new feature or improvement for this library.
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        # Feature request

        👋 Hi! Thanks for taking the time to suggest an improvement.

        **Please fill the following carefully before opening a new request ❗**
        *(Your request may be closed if it doesn't provide the required pieces of information)*
  - type: checkboxes
    attributes:
      label: Before submitting a new request
      description: Please perform simple checks first.
      options:
        - label: I checked for possible duplicate requests, with possible answers.
          required: true
        - label: This feature is related to this library and not to my own app or another package.
          required: true
  - type: textarea
    id: problem
    attributes:
      label: Use case / problem
      description: |
        Provide a clear and concise description of the problem you are trying to solve.
        What are you currently unable to do, or what is harder than it should be?
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
      description: |
        Describe the solution you'd like. If it affects the public API, show example usage / props / method signatures.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Describe any alternative solutions or workarounds you've considered.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or references about the feature request here.
    validations:
      required: false
